include: package:lints/recommended.yaml

analyzer:
  exclude:
    - example/**
    - flutter_examples/**

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    public_member_api_docs: true
