include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - example/**
    - flutter_examples/**

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    package_api_docs: true
    public_member_api_docs: true